// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvqvixtwfymtyehwvaet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2cXZpeHR3ZnltdHllaHd2YWV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTE4MjEsImV4cCI6MjA3MjU4NzgyMX0.vuNNPYlwEQum9mChGkGw5d2eDFFWWgS4HYOqJl_7kfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});